# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('extension_name', models.CharField(blank=True, max_length=5)),
                ('birth_day', models.DateField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=students.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('father_name', models.CharField(max_length=120, verbose_name="Father's full name")),
                ('mother_name', models.CharField(max_length=120, verbose_name="Mother's maiden name")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
