# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20161208_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lrn',
            new_name='lrn_or_id_number',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='sex',
            new_name='gender',
        ),
    ]
