# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170610_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(help_text='Format for date <em>yyyy-mm-dd<em>'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_name',
            field=models.CharField(help_text="Full name of your mother's maiden name.", max_length=120, verbose_name="Mother's maiden name"),
        ),
    ]
