# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semister',
            name='semister',
            field=models.CharField(choices=[('First Semester', '1st Sem'), ('Second Semister', '2nd Sem')], max_length=15),
        ),
    ]
