# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161213_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('Humanities', 'HUMMS'), ('Science', 'STEM'), ('Arts and Design', 'ARTS & DESIGN'), ('Sports', 'SPORTS'), ('Technical Vocational', 'TVL')], max_length=22)),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolYear')),
            ],
        ),
        migrations.AddField(
            model_name='strand',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Track'),
        ),
    ]
