# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_department_schoolyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['app_name'],
            },
        ),
    ]
