# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sidenav'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_fee', models.FloatField()),
            ],
        ),
    ]
