# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20170306_1016'),
        ('main', '0008_subjectfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectFee',
        ),
    ]
