# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_subjectfee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semister',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='semister',
            new_name='semester',
        ),
    ]
