# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170228_0233'),
        ('instructors', '0004_auto_20161228_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
    ]
