# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_auto_20170513_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='id_number',
        ),
        migrations.AddField(
            model_name='instructor',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='employment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructors.EmploymentStatus'),
        ),
    ]
