# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classschedules', '0003_auto_20170302_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classschedules.Block'),
        ),
    ]
