# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classschedules', '0006_subjectfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectfee',
            name='miscellaneous_fees',
        ),
    ]
