# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classschedules', '0008_auto_20170306_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='total_number_of_modules',
            field=models.IntegerField(default=8),
        ),
    ]
