# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_strand_strand'),
        ('instructors', '0003_instructor_employment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('descriptive_title', models.CharField(max_length=120)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor')),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolYear')),
                ('semister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Semister')),
            ],
        ),
    ]
