# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_schoolyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semister',
        ),
    ]
