# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_subject_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_fee',
            field=models.FloatField(),
        ),
    ]
