# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20170306_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=3),
        ),
    ]
